[package]
default-run = "netpulse"
name = "netpulse"
version = "0.1.0"
edition = "2021"
publish = true
authors = ["Christoph J. Scherr <software@cscherr.de>"]
license = "MIT"
description = "Keep track of if your internet is still alive, collect stats against a crappy ISP"
readme = "README.md"
homepage = "https://github.com/PlexSheep/kauma"
repository = "https://github.com/PlexSheep/kauma"


[dependencies]
getopts = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
daemonize = "0.5"
rusqlite = "0.32.1"

[[bin]] # client
name = "netpulse"
path = "src/bins/netpulse"

[[bin]] # daemon
name = "netpulsed"
path = "src/bins/netpulsed"
